### ISSUE TITLE
Fix "Add 'Unknown (6)'" semester

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#111]
Beyond summer session 2, we should not see any text for more sessions to add to our plan.

![](http://i.imgur.com/RyvGyDi.jpg)

**Comment by hawkrives** [comment]
Ah yes, I spotted that this morning. Give me a minute…

**Comment by hawkrives** [comment]
What do you think? Change the text to, like, "No More Semesters", or just hide the button?

**Comment by drewvolz** [comment]
Hidden would be preferable.
