### ISSUE TITLE
Changing the matriculation year forward sends Gobbldygook into an infinite loop

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#114]
It's been happening since at least January...

-----

Ok. Found the source of the loop. It's in findMissingNumberBinarySearch.

Or rather, it's in findFirstAvailableYear.

It was duplicating the matriculation year if you had a schedule for that year

Then it ran a binary search on the list of years, which entered an infinite loop if there were duplicate items.

So if you changed the matriculation year forward after making schedules, it would die.

**Comment by hawkrives** [comment]
That was solved by only adding the matriculation year if it doesn't already exist in the list of years (as pulled from the schedules).

**Comment by drewvolz** [comment]
Nice! This has been plaguing us for a while. Thanks for solving it!
