### ISSUE TITLE
The user is forced to reload the page after Areas of Study (or Courses) are updated 

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#120]
They shouldn't have to.

**Comment by drewvolz** [comment]
Woah. I did not notice that one.

**Comment by hawkrives** [comment]
I think this one has been resolved. 

I think.

… now, how can I test it?

**Comment by hawkrives** [comment]
YES! It works.

I tested by picking a random course from the DB, in this case `77185` – what used to be "FLC - Chinese".

```js
database.store('courses').get(77185).then(c => {c.title = 'KIK - Chinese'; return database.store('courses').put(77185, c)}).then(console.log.bind(console))
```

I ran that, to pull it out of the db and change it's title, then manually dispatched the `refreshCourses` action, and voila! Updated course in the table.
