### ISSUE TITLE
Link to catalog does not work for BA degree

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#127]
The link that is being pointed to is [here](http://catalog.stolaf.edu/academic-programs/bachelor-of-arts/) when it really should be both [here](http://catalog.stolaf.edu/curriculum/graduate-requirements-degrees/) and [here](http://catalog.stolaf.edu/curriculum/graduate-requirements-degrees/general-education-requirements-ba/).

**Comment by hawkrives** [comment]
Yes, although it should actually only point to the second link. 

The first link is the graduation requirements; things like "you need 35 credits" and "three of your last four courses must be taken on Olaf's campus". (Paraphrased, of course). 

The second one is just gereqs; FYW, WRI, things like that. 

Currently, the BA degree in Gobbldygook only handles the general education requirements, not the general graduation ones.

**Comment by hawkrives** [comment]
But, to come back to the issue at hand, yes, it does currently point to the wrong location.

**Comment by drewvolz** [comment]
You have a valid point in saying that we do not evaluate the first link's requirements... but would it hurt providing a link to them? That way, if someone is for some reason only listening to the output of the application, they could have access to the full set of graduation requirements? Unless they will be implemented in the near future...
