### ISSUE TITLE
Scrollbar jumps on overrides toggle

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#1342]
Ubuntu 14.04
Chrome 55.0.2883.87

When I enable or disable an override on the `area-of-study-group` sidebar (degrees, concentrations, emphases), the view scrolls back up to the top of the screen. I've noticed this behavior does not take place on Chrome 56 for macOS Sierra 10.12.3.

**Comment by hawkrives** [comment]
darn `overflow:scroll` sections.

**Comment by hawkrives** [comment]
this behavior is now happening in Chrome for macOS, as well.

**Comment by hawkrives** [comment]
Closed by #2280
