### ISSUE TITLE
Infinite loop appending on search page

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#1784]
Involves #1623 

Issue with https://gobbldygook.site/search/

https://gobbldygook.site/search/ appends a search query in an infinite loop
https://hawkrives.github.io/gobbldygook/search/ does not

**Comment by hawkrives** [comment]
not fixed

**Comment by hawkrives** [comment]
appears to be fixed now

(I pushed a bunch of stuff to master)

**Comment by hawkrives** [comment]
something in https://github.com/hawkrives/gobbldygook/compare/dcf4090ca12472c6e160c317631466f1712878d0...5f9067038bb3cd69bab4bd6fd5ef5fc51fe322c9

well that's a short diff

anyway, it's entirely possible that netlify hadn't actually deployed from #2137 and I fixed that instead

**Comment by drewvolz** [comment]
Retrieving [https://gobbldygook.site/favicon.ico](https://gobbldygook.site/favicon.ico) reveals the infinite appending behavior is still at large.

**Comment by hawkrives** [comment]
I can now reproduce this on:

- /student
- /areas

and probably more
