### ISSUE TITLE
Computer Science major needs updating

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#181]
computer-science-2014-15.yaml should include hipercic/hipercic lab as options for the elective credit.

**Comment by hawkrives** [comment]
What's their course numbers?

**Comment by drewvolz** [comment]
ID 259
ID 259 A (lab)
ID 259 B (lab)

**Comment by hawkrives** [comment]
Are there any other changes we should be aware of for this year?

**Comment by drewvolz** [comment]
To any major, or to the Computer Science major?

**Comment by hawkrives** [comment]
CS. We kinda only support one revision a year… well, no we don't; as long as we don't make too many changes, we'd be fine to make other changes.

**Comment by hawkrives** [comment]
Do you want to make a PR to add them?

**Comment by drewvolz** [comment]
Soon, very soon yes.

**Comment by hawkrives** [comment]
Closed by fa22b386427a88bef8b37295a82b8b4a91bbbe56 and a94153a70f9edefb2377bc1b96d88d5eb6c1ae4f?
