### ISSUE TITLE
Button in course in sidebar search 

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#213]
The button renders interestingly.

![Image of Sidebar](http://i.imgur.com/HIfjTta.png)

**Comment by hawkrives** [comment]
… I don't think it's supposed to be showing up at all

**Comment by hawkrives** [comment]
I'm going to mark this as closed; it's no longer applicable with the new modal course info boxes.

**Comment by drewvolz** [comment]
Fine by me.
