### ISSUE TITLE
Keyword 'term:' returns 

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#214]
I am unable to search for a term in the sidebar search. I tried "term:spring" and this is returned in the console:

Uncaught #<CustomEvent>
t @ gobbldygook.3.0.0-beta2.js:17
w @ gobbldygook.3.0.0-beta2.js:5
t.fireRejectionEvent @ gobbldygook.3.0.0-beta2.js:5
t._notifyUnhandledRejection @ gobbldygook.3.0.0-beta2.js:5
r._drainQueue @ gobbldygook.3.0.0-beta2.js:5
r._drainQueues @ gobbldygook.3.0.0-beta2.js:5
drainQueues @ gobbldygook.3.0.0-beta2.js:5

**Comment by hawkrives** [comment]
Can you do `term:3` – wait
oh
`term` expects a <year>+<semester> term

If you just want spring stuff, you'll need `semester:3`, `sem:3`, or `sem:spring`

**Comment by drewvolz** [comment]
Ah! My misunderstanding. Thanks.

**Comment by hawkrives** [comment]
That thing needs docs. Badly. But it also needs to be rebuilt. So. It exists. Maybe thanksgiving break...
