### ISSUE TITLE
Disable undo button on newly created student

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#215]
When I create a new student, the undo button is enabled. Undo-ing and hitting "back" (student list button) deletes the student.

**Comment by hawkrives** [comment]
here are words: can we re-orient the `students` reducer around calling a set of `student` (singular) reducers?

like in https://github.com/rackt/redux/blob/master/docs/basics/ExampleTodoList.md.

then each `student` reducer can be undoable, rather than the entire set.

**Comment by hawkrives** [comment]
Solved in an experimental branch.

**Comment by hawkrives** [comment]
Solved!
