### ISSUE TITLE
"Add course to schedule" button should be hidden, not disabled, when searching courses without an active student

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#2204]
The course detail "add to schedule" is not enabled on "/search"

**Comment by hawkrives** [comment]
Which `/search`? The one in the sidebar, `/s/:id/search`, or the one at the student list, `/search`?

**Comment by drewvolz** [comment]
The one on the student list

**Comment by hawkrives** [comment]
That will never be active. It's disabled for a reason 😛 

I'll change this issue to track hiding it, instead.
