### ISSUE TITLE
Cannot "sort by" on course index search

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#2206]
Group by works but sort by does not on "/search"

**Comment by hawkrives** [comment]
Sort By isn't working on the student page, either

**Comment by hawkrives** [comment]
It's because of `sortByArgs` in https://github.com/hawkrives/gobbldygook/blob/3dd5ac45017997581dc366eb4882e6c7f3922238/modules/gob-web/modules/course-searcher/redux/reducers.js#L89-L91

where it sorts by year, deptnum, semester, section, and _then_ your chosen key

**Comment by hawkrives** [comment]
Fixed locally; PR incoming
