### ISSUE TITLE
Search animation looks off

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#2207]
The way it spins is a little funky.

<img src="https://user-images.githubusercontent.com/5240843/38770044-ee17168c-3fc9-11e8-8c57-9920313b669c.gif" width=300 />

<img src="https://user-images.githubusercontent.com/5240843/38770075-6329657e-3fca-11e8-8b2d-a568322e1940.gif" width=500 />

**Comment by hawkrives** [comment]
This was fixed by bugfixes in #2209
