### ISSUE TITLE
Responsive view is difficult to use

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#2208]
When I search, it isn’t immediately apparent that I have to scroll the top half of the screen down to see search results. It also confused me when I had to scroll the bottom half of the view to move the rest of the content.

**Comment by hawkrives** [comment]
There is no mobile view :waves hand:

**Comment by drewvolz** [comment]
Updated title.

**Comment by hawkrives** [comment]
There is only desktop :waves hand:

**Comment by drewvolz** [comment]
I was able to load it on my mobile phone 👍

**Comment by drewvolz** [comment]
So we should look at that!

**Comment by hawkrives** [comment]
Closed by #2280
