### ISSUE TITLE
Filtering the list of courses for "a" causes UI to freeze

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#2211]
I'm not sure what's happening. I'm doing this on the home view rather than the schedule view.

**Comment by drewvolz** [comment]
I am then unable to view the search box again once I close it.

**Comment by hawkrives** [comment]
I cannot reproduce this in Chrome 68

**Comment by hawkrives** [comment]
I also cannot reproduce on Safari 11.1

**Comment by hawkrives** [comment]
Nor can I reproduce on Firefox Nightly 61.0a1

**Comment by hawkrives** [comment]
@drewvolz Would you mind attaching a screen recording?

**Comment by drewvolz** [comment]
Happens for me on Chrome 68.0.3397.0 (Official Build) canary (64-bit)

**Comment by hawkrives** [comment]
Then I must be doing something differently than you are.

**Comment by drewvolz** [comment]
I type the letter "a", hit enter, wait 10 seconds, then try to interact with the UI. If I am able to close to the search box, I am unable to open it again or interact with the rest of the app.

**Comment by hawkrives** [comment]
… okay, now I'm confused. The student lister filtering box filters dynamically. 

Are you talking about course search again? Because there's no close button on the list filter…

Can you send a screenshot or recording?

**Comment by drewvolz** [comment]
...I meant courses. Sorry.

**Comment by hawkrives** [comment]
Don't search for "a". 

If you wait about five minutes, the app will either crash or finish rendering all of the result items. 

The proper way to solve this is by implementing a virtualized list view for the search results, but I haven't gotten around to that yet. 

So, don't search for short queries. 

:smile:

**Comment by drewvolz** [comment]
That's not a solution though.

**Comment by hawkrives** [comment]
I said that the solution is to change how the list is rendered.

**Comment by drewvolz** [comment]
Right, so why close the issue if it isn't fixed?
