### ISSUE TITLE
Unhandled Promise Rejection: TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#2225]
> Unhandled Promise Rejection: TypeError: Right side of assignment cannot be destructured

Error happens when importing an exported student from the live copy to the local copy.

My browser: Safari

**Comment by drewvolz** [comment]
```js
function shouldTakeAction({ type }) {
	return whitelist.has(type);
}
```

![2018-07-04 11 19 32](https://user-images.githubusercontent.com/5240843/42289339-2686dea2-7f7c-11e8-8dfa-9f2131d62186.jpg)

**Comment by drewvolz** [comment]
...and the majority of my first semester courses are undefined

<img width="840" alt="screen shot 2018-07-04 at 11 20 53 am" src="https://user-images.githubusercontent.com/5240843/42289392-664065ea-7f7c-11e8-86b0-6076a374c147.png">

**Comment by drewvolz** [comment]
Output:

```js
function shouldTakeAction({type}){return whitelist.has(type);}
```

**Comment by drewvolz** [comment]
I think #1181 is involved

**Comment by hawkrives** [comment]
#1181 is the cause of https://github.com/hawkrives/gobbldygook/issues/2225#issuecomment-402530247, but not of the OP.

**Comment by hawkrives** [comment]
Meanwhile, the root cause here is that `undefined` is being passed to `shouldTakeAction` for some reason.

**Comment by hawkrives** [comment]
Not fixed, judging by

**Comment by drewvolz** [comment]
I like the concept of the permanently shareable (secret) links that the G-Suite offers for docs, drive, etc. Something akin to that?

**Comment by hawkrives** [comment]
I was thinking more along the lines of encode the JSON object into a query parameter, like [Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9fPz8Aeiz8ABVbABFbJHxC6AV9Gzh8akMoOggAW394tganDN19RJa+C0MYIQA6VHIafAYBoeG6huaGDwAqfABGAFEAagB2N2GYCABlGGpw5kXZuAAHEkMwOAYs-n5h57pNrJxmSUFBN3T4rUOLF4gAeOg4ez4MC3TSaAByhiacB4CmIZEoNHoCnwuBguh4wAABgBNaz4QxsfD2HDaA7UBLoJoAIyc+AAJMBGS0XESXPhLNY7I5qITBdUHE4XAA+AGZfCgzQnaDMaVc0KcZjDTQkHD3Bj4AAMklW+D2BwAqlcrk4AMKGUyLfCbKRsMJcbW6-Wrc0QAAyEAA7naHQ8PC5QVkldQVbLAX4WG7NcMEHRNBQcEMGBI-vgAPwCECF-ClRVXer4JUATwJwGAkHI1FKSn40irChcMokhcjmnLUGl+BcGT8oLgTTj-Bg6qTcDkw58MEj47j8q5DG0ulg-3jmQLgleIBHmVKgiCggXx8jEPs0rSPigLhA4hAECuuGgmmQoEpMcDAAVKQQL8UEMewIBwOhnxAZk6jAABrDhDnLMAzmQE50DMEBwlMagYH-OpmCaQxkCMEwsIAK00AAPAAhODEJgQ4kTgP1wjgUjjFMF9y2oXDkBgwxmRraBoKuU5YAzOghmQAAOY0QHEiBTAoOorgE8S4FwxxoLYABHdAcDYAjDCIkikDI7iQFMJocHQ6hMJfbQuF0ABFdAIHgTjyJfGAhKkmSkAAJl8uodDOW1mmIgSoGgDiX2qPIhJAyy4E7IA) or [Babel's REPL](http://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=FAFwngDgpgBACgJwPYQM4wLwwN4F8DcoksAyiAIYixbbAwwCWAdlUwCZRsBKUAxgxAZQWALhioQCZgHMANHRgI-AoSwCSTAGZIxAfjzz6g3gGsZAVQhiSUEAB4JUptIB8hmOQBu5BgBtyAEa-UGIAgggI5GB2cCbSGtpuCqgArgEAtgwgIDJiAUhIweRMwATAwFAAHhBICCAwvP6o6HAMpikQMFWsbOg85LwgAHQAwkjpNUzC9ogoqLIwZJRQLjjJFFSYa_T0zD2cPPyC02IARKfu9EpHqiAJOjBMKb6-lzDGZs6WYlMA7ou2BySGQuAAUAG0ALoASjeXh8_iCIRgULeqQyWRyzjEmnIvlQUAUZVwwCAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=true&presets=react%2Cstage-2%2Cstage-3&prettier=false&targets=&version=6.26.0&envVersion=)

**Comment by hawkrives** [comment]
For future reference, this was only occurring when a student was first imported.
