### ISSUE TITLE
Lack of space between Avatar and StudentSummary

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#2226]
1 | 2
--|--
<img width="284" alt="screen shot 2018-07-04 at 10 52 15 am" src="https://user-images.githubusercontent.com/5240843/42289825-0341aca8-7f7f-11e8-8b54-761f8441eedc.png"> | <img width="265" alt="screen shot 2018-07-04 at 11 31 13 am" src="https://user-images.githubusercontent.com/5240843/42289826-035d3afe-7f7f-11e8-9850-66547e8cfa0d.png">

**Comment by hawkrives** [comment]
Cannot replicate on Chrome 70.0.3498.0

![image](https://user-images.githubusercontent.com/464441/43051597-f47855e8-8de1-11e8-9d62-df966993b5c0.png)

**Comment by drewvolz** [comment]
I don't know what's going on but I believe I'm experiencing it still on Chrome 70.0.3500.0.

1 | 2
--|--
<img width="266" alt="gb incomplete" src="https://user-images.githubusercontent.com/5240843/43085628-acba278c-8e58-11e8-8fb9-4390d16ed77e.png"> | <img width="265" alt="gb complete" src="https://user-images.githubusercontent.com/5240843/43085629-acdc3aca-8e58-11e8-963f-702dc3a7ca17.png">

<img width="677" alt="chrome version" src="https://user-images.githubusercontent.com/5240843/43085642-b905cfd2-8e58-11e8-8f8d-728e8d65c815.png">

**Comment by drewvolz** [comment]
Well, I'm not seeing the twice-as-much-space, which closes this issue. But I'm seeing the title get a little close to the circle. So we can close this out.

**Comment by hawkrives** [comment]
and, hey! Now I can replicate.

Initial findings: `.intro` has no margin set. Not sure if it's supposed to.

**Comment by hawkrives** [comment]
```scss
.student-letter {
	margin: 5px auto 10px;
}
```

but `margin: 0px;` on AvatarLetter's StyledComponent
