### ISSUE TITLE
Use "tabular nums" in the progress notification texts

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#2273]
![image](https://user-images.githubusercontent.com/464441/45962362-4ec95200-bfe6-11e8-8208-3677159a2923.png)

The numbers should get `font-variant-numeric: tabular-nums;` applied to them, so that a `1` takes up the same horizontal space as a `9`. This will prevent the bar and numbers from moving around as the load happens.

@drewvolz, here's a notification.

**Comment by drewvolz** [comment]
Closed by #2280

**Comment by hawkrives** [comment]
Not #2280; #2281, which isn't merged yet

**Comment by drewvolz** [comment]
Good catch. Sorry.
