### ISSUE TITLE
SIS dataset has no info on MUSPF or study-abroad courses

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#27]
Why?

**Comment by hawkrives** [comment]
Regarding the MUSPF courses: I talked to Craig earlier. He verified that MUSPF is hard coded to be not returned; then he noticed that there's a check for User.isSuperUser, and said that IT could easily (~15min) add a check and role for User.isDeveloper, too.

We would "just" need the Registrar's approval for them to make the change and grant us access, which Craig and Andy said would take 15min, max.

I'm probably going to go by and talk to them next week.

Craig also said (and Andy nodded) that we have the full support of IT for that, but that he wasn't sure how useful that would be.

**Comment by drewvolz** [comment]
@hawkrives Excellent. This conversation should most likely occur in the form of an email in support of this decision from IT to the Registrar.

**Comment by hawkrives** [comment]
Well, I didn't make it by last week.

I'm kinda falling back towards my old "we can just generate [the courses we don't have in the database] as fabrications or something" viewpoint.

@drewvolz what do you think?

**Comment by drewvolz** [comment]
Would you be considering this because you "developer" privileges in the system? Sure, anything not listed in the public SIS could be a fabrication. Is your thinking that it would be just a simpler way to go?

**Comment by hawkrives** [comment]
Developer privileges would solve this particular case, but ... I think we would still want the "generate fabrications from unknown courses" behavior for any future weirdness. 

That, and I ... well, TBH, I'm both lazy and nervous about approaching Mary Cisar again. That's probably my original impetus.

**Comment by drewvolz** [comment]
Your honesty is understandable. It makes sense to do it the fabrication way.

**Comment by drewvolz** [comment]
Any updates?

**Comment by hawkrives** [comment]
(from https://github.com/hawkrives/gobbldygook/issues/27#issuecomment-73535804)
> I'm kinda falling back towards my old "we can just generate [the courses we don't have in the database] as fabrications or something" viewpoint.

This is what `master` does, now that there is a SIS export page; any courses that aren't in the local database get generated as fabrications at import time.
