### ISSUE TITLE
Write an algorithm for condensing a conflict-free schedule from a group of courses and course section

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#39]
(This stems from the fact that the SIS degree audit operates on the generic *courses*, rather than any specific instance of a course.)

The course table from the degree audit can get us close to an instance of a course, by way filtering the total group of courses down by `year`, then `semester`, then `dept`, then `num`, then `name`. This will leave us with a set of `N` possibilities, where `N` is the number of sections offered of that course.

Therefore, we need an algorithm which, given a large list of courses each of which has one or more possible sections, can resolve to a schedule with no time conflicts.

**Comment by drewvolz** [comment]
This is mostly addressed now, however, we still want to reevaluate our focus on classes instead of courses... and possibly switch to using classes instead of courses.

**Comment by hawkrives** [comment]
This is now going to be closed in favor of #72 and #73, as well as the [Courses, not classes](https://github.com/hawkrives/gobbldygook/milestones/Courses,%20not%20classes) milestone.
