### ISSUE TITLE
Write a browser extension to handle SIS data fetching

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#860]
Idea from @drewvolz

Write a Chrome/Opera/Firefox/Edge/Safari [web extension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) that pulls data from the SIS and passes it to Gobbldygook.
- Doesn't require me to run a server or handle credentials
- It says "install this", then there's a button that talks to the extension, which requests the pages and parses them
- and if you're not logged in, it makes you go log in yourself

**Comment by drewvolz** [comment]
This is being worked on here [https://github.com/hawkrives/gobbldygook-web-ext](https://github.com/hawkrives/gobbldygook-web-ext)

**Comment by hawkrives** [comment]
Now pretty much complete and living at [hawkrives/gobbldygook-web-ext](https://github.com/hawkrives/gobbldygook-web-ext). Next up: adding "install" buttons to the SIS Student Import screen.

**Comment by hawkrives** [comment]
So this almost works now. However, the gobbldygook bit that shows the "add to browser" bit is causing an infinite loop.

**Comment by hawkrives** [comment]
it also has a problem with courses that it can't find in the database; it returns NaN instead of the bits taht we fetched from SIS.

**Comment by hawkrives** [comment]
Closed by the new SIS json export / import features. Will be further buried by future SIS integrations.
